<?php

/**
 * 数据库表与字段注释映射（co_crmv5 全库）。
 *
 * 文件功能：
 * - 提供 77 张表的“表作用注释”与 194 个缺失字段的“字段详细注释”。
 * - 注释语义与代码强相关：枚举值来自模型/服务常量，用途来自业务闭环链路
 *   （注册/入金/出金/返佣 Saga/MT4 预配/认证/销户等）。
 * - 由 artisan 命令 db:annotate-columns 消费：生成 ALTER TABLE 并执行或导出 SQL。
 *
 * 适用场景：
 * - 开发库信息补全：php artisan db:annotate-columns
 * - 导出可执行 SQL：php artisan db:annotate-columns --export=database/sql/column_comments.sql
 *
 * 说明：
 * - 表名/字段名与 information_schema 精确匹配；已存在的详细注释不会被覆盖。
 * - 字段注释键格式：'表名.字段名' => '注释'。
 */
return [

    // ==================== 表作用注释（77 张） ====================
    'tables' => [
        'admin_agent_bindings' => '后台管理员与代理商绑定关系表：用于后台数据范围授权，限定管理员只能管理其绑定的代理树。',
        'admin_auth_review_outboxes' => '后台认证审核事件 Outbox 表：保存待处理的认证审核请求，保证审核状态与外部系统操作最终一致。',
        'admin_login_logs' => '后台管理员登录日志表：记录每次登录的账号、IP、UA 与结果，用于后台安全审计。',
        'admin_logins' => '后台管理员登录会话表：维护管理员当前登录会话与 JWT 绑定，支撑 SSO 单点登录。',
        'admins' => '后台管理员账号表：管理员身份、登录凭证、状态与 SSO JWT 绑定信息。',
        'agent_descendants' => '代理树后代关系表：扁平化存储每个代理的下级代理与客户关系，加速代理树范围查询。',
        'agent_levels' => '代理商等级表：定义代理等级与对应的佣金率/结算规则。',
        'app_versions' => 'APP 版本管理表：客户端版本号、下载地址与强制更新配置。',
        'batch_fail_records' => '批量操作失败记录表：入金/出金/信用导入等批量任务的失败明细，供重试与对账。',
        'big_agent_login_logs' => '大代理商登录日志表：大代理（Big Agent）登录审计。',
        'big_agents' => '大代理商账号表：大代理身份、登录凭证与状态。',
        'blacklists' => '黑名单表：禁止登录或交易的用户/设备/IP 清单。',
        'cancel_applies' => '销户申请审核表：用户销户申请与后台审批流转（通过/驳回）。',
        'commission_rebate_payouts' => '点差返佣发放记录表：按点差计算的返佣发放流水，用于对账与统计。',
        'commission_records' => '佣金记录表：代理佣金结算明细（实时/周期），驱动前台返佣查询。',
        'commission_transfer_outbox' => '佣金转账 Saga 事件 Outbox 表：待投递的转账事件（withdraw/deposit/compensation），保证本地事务与外部 MT4 操作的最终一致。',
        'commission_transfers' => '佣金转账 Saga 主表：代理商向直属下级转账的幂等订单与状态机（verify/withdraw/deposit/compensation），含人工对账字段。',
        'countries' => '国家表：注册与资料填写可选国家。',
        'country_langs' => '国家多语言表：国家名称的多语言文案。',
        'country_translations' => '国家翻译表：国家名称各语言翻译条目。',
        'credit_imports' => '信用额导入表：后台批量导入用户信用额的任务与结果。',
        'data_operation_logs' => '数据操作日志表：重要数据变更的审计记录（谁/何时/改了什么）。',
        'deposit_imports' => '入金导入表：后台批量导入入金记录的任务与结果。',
        'deposit_records' => '入金记录表：用户入金订单主表（申请/支付/结算/退款全状态）。',
        'failed_jobs' => 'Laravel 失败队列任务表：队列任务执行失败后的持久化负载。',
        'gift_items' => '礼品条目表：可兑换礼品定义与库存。',
        'gift_shipments' => '礼品发货表：用户礼品兑换申请与发货状态。',
        'group_configs' => '组别配置表：交易组（MT4 Group）配置项，用户开户与转组使用。',
        'id_sequences' => 'ID 序列生成表：为 user_id 等业务主键生成连续唯一编号。',
        'languages' => '语言表：系统支持的语言定义。',
        'mail_settings' => '邮件配置表：系统邮件发送配置（SMTP/发件人）。',
        'menus' => '后台菜单表：后台侧边栏菜单结构（含 Lucide 图标名）。',
        'migrations' => 'Laravel 迁移记录表：已执行迁移文件与批次号。',
        'mt4_configs' => 'MT4 服务配置表：MT4 Manager API 连接配置（地址/账号/密钥）。',
        'mt4_prices' => 'MT4 行情价格表：品种最新报价镜像。',
        'mt4_trades' => 'MT4 交易记录表：MT4 服务器订单镜像（开/平仓）。',
        'mt4_users' => 'MT4 用户同步表：MT4 开户账号与本地用户映射。',
        'news' => '新闻公告表：前台公告与后台资讯。',
        'news_langs' => '新闻多语言表：新闻标题/内容的多语言文案。',
        'offweb_feedbacks' => '站外反馈表：非登录用户提交的意见反馈。',
        'operation_logs' => '后台操作日志表：管理员关键操作审计（增删改查）。',
        'password_resets' => '密码重置令牌表：忘记密码流程的临时令牌。',
        'payment_channels' => '支付通道表：入金通道配置（网关/费率/状态）。',
        'payment_settlement_outbox' => '入金结算事件 Outbox 表：入金到账后待投递的结算事件（settle/create_claim），保证入账与 MT4 入金一致。',
        'permissions' => '权限表：后台菜单/接口权限点（含图标与路由）。',
        'personal_access_tokens' => 'Sanctum 个人访问令牌表：API 令牌认证。',
        'rights_settlement_temps' => '权益结算临时表：权益汇总计算中间结果。',
        'rights_settlements' => '权益结算表：账户权益汇总（余额/净值/保证金），驱动权益统计页。',
        'role_data_scopes' => '角色数据范围绑定表：角色可管理的数据范围（全部/代理树/本人）。',
        'role_permissions' => '角色权限绑定表：角色与权限点多对多。',
        'roles' => '角色表：后台角色定义（含默认菜单）。',
        'spread_configs' => '点差配置表：品种点差与返佣计算参数。',
        'symbol_prices' => '品种行情价格表：交易品种报价镜像（供持仓/风控计算）。',
        'sys_dicts' => '系统字典表：通用字典项（下拉选项等）。',
        'system_configs' => '系统配置表：键值对系统参数。',
        'trans_apply_logs' => '转组申请审核日志表：用户转组申请与后台审批流转。',
        'user_addresses' => '用户收货地址表：礼品兑换收货地址。',
        'user_auths' => '用户认证资料表：实名认证、银行卡绑定与审核状态（含临时字段）。',
        'user_auths_backup_20260613035755' => '用户认证资料历史备份（2026-06-13 数据修复前快照，仅供追溯，不参与业务）。',
        'user_auths_backup_20260613040006' => '用户认证资料历史备份（2026-06-13 数据修复前快照，仅供追溯，不参与业务）。',
        'user_images' => '用户图片表：头像/证件等上传文件引用。',
        'user_infos' => '用户信息主表：用户资料、资金快照、MT4 同步、代理关系与风控状态。',
        'user_infos_backup_20260613035755' => '用户信息历史备份（2026-06-13 数据修复前快照，仅供追溯，不参与业务）。',
        'user_infos_backup_20260613040006' => '用户信息历史备份（2026-06-13 数据修复前快照，仅供追溯，不参与业务）。',
        'user_login_logs' => '用户登录日志表：前台用户登录审计（时间/IP/设备）。',
        'user_logins' => '用户登录账号表：前台用户登录凭证（邮箱/手机/密码哈希）。',
        'user_logins_backup_20260613035755' => '用户登录账号历史备份（2026-06-13 数据修复前快照，仅供追溯，不参与业务）。',
        'user_logins_backup_20260613040006' => '用户登录账号历史备份（2026-06-13 数据修复前快照，仅供追溯，不参与业务）。',
        'user_mt4_provisioning_outbox' => '用户 MT4 开户预配 Outbox 表：注册成功后待执行的 MT4 开户事件，保证本地注册与远端开户最终一致。',
        'user_onlines' => '用户在线状态表：登录用户在线心跳与强制下线标记。',
        'user_trades' => '用户交易记录本地镜像表：MT4 交易数据的本地冗余，支撑前台查询与风控。',
        'users' => 'Laravel 默认用户表：框架默认认证用户（业务前台用户见 user_logins/user_infos）。',
        'voucher_infos' => '凭证信息表：用户存款凭证提交与后台审核。',
        'whs_exp_zeros' => '爆仓清零记录表：风控爆仓清零操作记录（含一键清零）。',
        'withdraw_imports' => '出金导入表：后台批量导入出金记录的任务与结果。',
        'withdraw_records' => '出金记录表：用户出金订单主表（申请/审核/打款/退款全状态）。',
        'withdraw_settlement_outbox' => '出金结算事件 Outbox 表：出金完成后待投递的结算事件（refund/complete），保证出金与 MT4 扣款一致。',
    ],

    // ==================== 缺失字段注释（194 个） ====================
    'columns' => [
        // ---------- admin_auth_review_outboxes（认证审核事件 Outbox，18 字段） ----------
        'admin_auth_review_outboxes.id' => '主键标识。',
        'admin_auth_review_outboxes.user_id' => '待审核业务用户标识。',
        'admin_auth_review_outboxes.active_user_id' => '处于活动审核流程的用户唯一标识。',
        'admin_auth_review_outboxes.admin_id' => '发起审核的管理员标识。',
        'admin_auth_review_outboxes.admin_name' => '发起审核的管理员名称。',
        'admin_auth_review_outboxes.request_ip' => '发起审核请求的 IP 地址。',
        'admin_auth_review_outboxes.status' => '处理状态：pending=待处理 / processing=处理中 / succeeded=成功 / failed=失败。',
        'admin_auth_review_outboxes.attempts' => '处理重试次数。',
        'admin_auth_review_outboxes.payload_ciphertext' => '审核请求负载密文，避免敏感资料明文落库。',
        'admin_auth_review_outboxes.payload_hash' => '审核请求负载 SHA-256 摘要，用于防篡改与幂等校验。',
        'admin_auth_review_outboxes.auth_snapshot_hash' => '认证资料快照 SHA-256 摘要，用于确认处理期间资料未变化。',
        'admin_auth_review_outboxes.available_at' => '可处理时间，用于失败后的退避重试。',
        'admin_auth_review_outboxes.locked_at' => '任务锁定时间，用于防止并发重复处理。',
        'admin_auth_review_outboxes.processed_at' => '审核任务处理完成时间。',
        'admin_auth_review_outboxes.last_error_code' => '最近一次处理失败的错误码。',
        'admin_auth_review_outboxes.created_at' => '创建时间。',
        'admin_auth_review_outboxes.updated_at' => '更新时间。',
        'admin_auth_review_outboxes.deleted_at' => '软删除时间。',

        // ---------- commission_transfers（返佣转账 Saga 主表，36 字段） ----------
        'commission_transfers.id' => '主键标识。',
        'commission_transfers.local_order_no' => '本地订单号（幂等与对账唯一键，格式如 CMT 前缀 + 日期 + 序号）。',
        'commission_transfers.source_user_id' => '转出方用户标识（发起转账的代理商）。',
        'commission_transfers.target_user_id' => '转入方用户标识（直属下级代理或直属客户）。',
        'commission_transfers.request_purpose' => '转账用途：verify=认证校验 / withdraw=出金 / deposit=入金 / compensation=补偿，决定 Saga 执行分支。',
        'commission_transfers.idempotency_key' => '幂等键：同一笔转账重复提交时去重，防止重复扣款。',
        'commission_transfers.payload_hash' => '请求负载 SHA-256 摘要：防篡改与重复投递校验。',
        'commission_transfers.payload_ciphertext' => '加密负载：包含密码等敏感字段的密文，避免明文落库。',
        'commission_transfers.amount' => '转账金额（十进制 18 位整数部分 2 位小数）。',
        'commission_transfers.remark' => '转账备注（用户填写或系统生成）。',
        'commission_transfers.status' => 'Saga 状态：pending=待处理 / processing=处理中 / succeeded=成功 / failed=失败 / manual_reconcile_required=需人工对账。',
        'commission_transfers.current_step' => '当前执行步骤：verify=校验 / withdraw=出金 / deposit=入金 / compensation=补偿。',
        'commission_transfers.manual_origin_step' => '人工介入前记录的执行步骤：对账完成后用于恢复或判定补偿路径。',
        'commission_transfers.reservation_status' => '资金预留状态：pending=未预留 / reserved=已预留 / released=已释放，防并发扣款。',
        'commission_transfers.small_limit_day' => '小额限制日：当日小额转账累计校验日期。',
        'commission_transfers.small_limit_key' => '小额限制键：按（用户+日期）维度累计小额转账金额。',
        'commission_transfers.withdraw_ticket' => 'MT4 出金单据号：Saga 出金分支的 MT4 侧凭证。',
        'commission_transfers.deposit_ticket' => 'MT4 入金单据号：Saga 入金分支的 MT4 侧凭证。',
        'commission_transfers.compensation_ticket' => '补偿单据号：异常补偿分支的 MT4 侧凭证。',
        'commission_transfers.source_balance_after' => '转出方操作后余额快照：对账用。',
        'commission_transfers.target_balance_after' => '转入方操作后余额快照：对账用。',
        'commission_transfers.attempts' => 'Saga 重试次数：每次调度递增，超过阈值转人工对账。',
        'commission_transfers.available_at' => '可处理时间（10 位时间戳）：重试退避后到达该时间才可再次调度。',
        'commission_transfers.locked_at' => '锁定时间：调度器领取任务时写入，防并发处理。',
        'commission_transfers.processed_at' => '处理完成时间：Saga 终态（成功/转人工）落库时间。',
        'commission_transfers.provider_reference' => '外部网关凭证引用：MT4 返回的交易引用号。',
        'commission_transfers.last_error_code' => '最近一次错误码：失败原因分类（网关/校验/超时）。',
        'commission_transfers.last_error_message' => '最近一次错误信息：人工排查详情。',
        'commission_transfers.created_at' => '创建时间（10 位时间戳）。',
        'commission_transfers.updated_at' => '更新时间（10 位时间戳）。',
        'commission_transfers.deleted_at' => '软删除时间（10 位时间戳）。',
        'commission_transfers.reconcile_decision' => '人工对账结论：confirmed=已确认 / refunded=已退款 / compensated=已补偿。',
        'commission_transfers.reconcile_external_reference' => '对账外部凭证：MT4 侧最终交易号或对账单引用。',
        'commission_transfers.reconcile_evidence' => '对账证据：对账时的余额/流水快照（JSON 文本）。',
        'commission_transfers.reconciled_by' => '对账人工号：后台管理员标识。',
        'commission_transfers.reconciled_at' => '对账完成时间（10 位时间戳）。',

        // ---------- commission_transfer_outbox（Saga 事件 Outbox，14 字段） ----------
        'commission_transfer_outbox.id' => '主键标识。',
        'commission_transfer_outbox.commission_transfer_id' => '关联佣金转账 Saga 主表标识。',
        'commission_transfer_outbox.event_type' => '事件类型：withdraw=出金 / deposit=入金 / compensation=补偿。',
        'commission_transfer_outbox.status' => '投递状态：pending=待投递 / processing=处理中 / succeeded=成功 / failed=失败。',
        'commission_transfer_outbox.attempts' => '投递重试次数。',
        'commission_transfer_outbox.payload_hash' => '事件负载 SHA-256：防重复投递与篡改。',
        'commission_transfer_outbox.available_at' => '可投递时间（10 位时间戳）：退避后重试。',
        'commission_transfer_outbox.locked_at' => '锁定时间：防并发投递。',
        'commission_transfer_outbox.processed_at' => '投递完成时间。',
        'commission_transfer_outbox.provider_reference' => '外部网关凭证引用。',
        'commission_transfer_outbox.last_error_code' => '最近错误码。',
        'commission_transfer_outbox.created_at' => '创建时间（10 位时间戳）。',
        'commission_transfer_outbox.updated_at' => '更新时间（10 位时间戳）。',
        'commission_transfer_outbox.deleted_at' => '软删除时间（10 位时间戳）。',

        // ---------- payment_settlement_outbox（入金结算 Outbox，15 字段） ----------
        'payment_settlement_outbox.id' => '主键标识。',
        'payment_settlement_outbox.deposit_record_id' => '关联入金记录表标识。',
        'payment_settlement_outbox.local_order_no' => '本地订单号（与 deposit_records.local_order_no 对应）。',
        'payment_settlement_outbox.event_type' => '事件类型：settle=结算入账 / create_claim=创建索赔。',
        'payment_settlement_outbox.status' => '投递状态：pending / processing / succeeded / failed。',
        'payment_settlement_outbox.attempts' => '投递重试次数。',
        'payment_settlement_outbox.payload_hash' => '事件负载 SHA-256。',
        'payment_settlement_outbox.available_at' => '可投递时间（10 位时间戳）。',
        'payment_settlement_outbox.locked_at' => '锁定时间。',
        'payment_settlement_outbox.processed_at' => '投递完成时间。',
        'payment_settlement_outbox.provider_reference' => 'MT4 入金凭证引用。',
        'payment_settlement_outbox.last_error_code' => '最近错误码。',
        'payment_settlement_outbox.created_at' => '创建时间（10 位时间戳）。',
        'payment_settlement_outbox.updated_at' => '更新时间（10 位时间戳）。',
        'payment_settlement_outbox.deleted_at' => '软删除时间（10 位时间戳）。',

        // ---------- withdraw_settlement_outbox（出金结算 Outbox，15 字段） ----------
        'withdraw_settlement_outbox.id' => '主键标识。',
        'withdraw_settlement_outbox.withdraw_record_id' => '关联出金记录表标识。',
        'withdraw_settlement_outbox.local_order_no' => '本地订单号（与 withdraw_records.local_order_no 对应）。',
        'withdraw_settlement_outbox.event_type' => '事件类型：refund=退款 / complete=完成。',
        'withdraw_settlement_outbox.status' => '投递状态：pending / processing / succeeded / failed。',
        'withdraw_settlement_outbox.attempts' => '投递重试次数。',
        'withdraw_settlement_outbox.payload_hash' => '事件负载 SHA-256。',
        'withdraw_settlement_outbox.available_at' => '可投递时间（10 位时间戳）。',
        'withdraw_settlement_outbox.locked_at' => '锁定时间。',
        'withdraw_settlement_outbox.processed_at' => '投递完成时间。',
        'withdraw_settlement_outbox.provider_reference' => 'MT4 出金/退款凭证引用。',
        'withdraw_settlement_outbox.last_error_code' => '最近错误码。',
        'withdraw_settlement_outbox.created_at' => '创建时间（10 位时间戳）。',
        'withdraw_settlement_outbox.updated_at' => '更新时间（10 位时间戳）。',
        'withdraw_settlement_outbox.deleted_at' => '软删除时间（10 位时间戳）。',

        // ---------- user_mt4_provisioning_outbox（MT4 开户预配 Outbox，17 字段） ----------
        'user_mt4_provisioning_outbox.id' => '主键标识。',
        'user_mt4_provisioning_outbox.user_login_id' => '关联用户登录表标识（user_logins.id）。',
        'user_mt4_provisioning_outbox.user_info_id' => '关联用户信息表标识（user_infos.id）。',
        'user_mt4_provisioning_outbox.user_id' => '业务用户标识（与 user_infos.user_id 一致，用于查询便捷）。',
        'user_mt4_provisioning_outbox.status' => '预配状态：pending=待预配 / processing=预配中 / succeeded=成功 / failed=失败。',
        'user_mt4_provisioning_outbox.attempts' => '预配重试次数。',
        'user_mt4_provisioning_outbox.reconciliation_attempts' => '对账重试次数：注册成功但远端未确认时的核对次数。',
        'user_mt4_provisioning_outbox.payload_ciphertext' => '预配负载密文（开户所需资料加密存储）。',
        'user_mt4_provisioning_outbox.payload_hash' => '预配负载 SHA-256。',
        'user_mt4_provisioning_outbox.available_at' => '可预配时间（10 位时间戳）。',
        'user_mt4_provisioning_outbox.locked_at' => '锁定时间。',
        'user_mt4_provisioning_outbox.processed_at' => '预配完成时间。',
        'user_mt4_provisioning_outbox.provider_reference' => 'MT4 开户凭证引用（mt4_code）。',
        'user_mt4_provisioning_outbox.last_error_code' => '最近错误码。',
        'user_mt4_provisioning_outbox.created_at' => '创建时间（10 位时间戳）。',
        'user_mt4_provisioning_outbox.updated_at' => '更新时间（10 位时间戳）。',
        'user_mt4_provisioning_outbox.deleted_at' => '软删除时间（10 位时间戳）。',

        // ---------- deposit_records 缺失字段（16 个，支付/结算硬化迁移新增） ----------
        'deposit_records.amount' => '申请入金金额（用户提交）。',
        'deposit_records.actual_amount' => '实际到账金额（支付成功后写入，默认 0.00）。',
        'deposit_records.provider_amount' => '网关侧金额（第三方返回，用于对账）。',
        'deposit_records.exchange_rate' => '汇率（法币/币种换算，默认 0.00000000）。',
        'deposit_records.idempotency_key' => '幂等键：防重复下单/重复回调入账。',
        'deposit_records.gateway_code' => '支付网关代码（bank_transfer/usdt_trc20/quick_pay 等）。',
        'deposit_records.merchant_id' => '商户号：网关侧商户标识。',
        'deposit_records.currency' => '币种（CNY/USDT 等）。',
        'deposit_records.payment_status' => '支付状态：pending=待支付 / paid=已支付 / expired=已过期 / failed=失败。',
        'deposit_records.settlement_status' => '结算状态：pending=待结算 / settled=已入账 / refunded=已退款。',
        'deposit_records.provider_payload_hash' => '网关回调负载 SHA-256：防回调伪造与重复入账。',
        'deposit_records.provider_order_result' => '网关创建订单原始返回（JSON），供人工核账。',
        'deposit_records.provider_create_started_at' => '调用网关创建订单的开始时间。',
        'deposit_records.provider_create_attempts' => '调用网关创建订单的重试次数。',
        'deposit_records.refund_mt4_ticket' => '退款 MT4 凭证：结算失败退款后的 MT4 单据号。',
        'deposit_records.refund_time' => '退款完成时间。',

        // ---------- withdraw_records 缺失字段（12 个，资金硬化迁移新增） ----------
        'withdraw_records.apply_amount' => '申请出金金额（用户提交）。',
        'withdraw_records.actual_amount' => '实际打款金额（扣除手续费后）。',
        'withdraw_records.fee' => '出金手续费（默认 0.00）。',
        'withdraw_records.exchange_rate' => '汇率（默认 0.00000000）。',
        'withdraw_records.rmb_fee' => '人民币口径手续费（默认 0.00）。',
        'withdraw_records.local_order_no' => '本地订单号（幂等与对账唯一键）。',
        'withdraw_records.idempotency_key' => '幂等键：防重复出金申请。',
        'withdraw_records.funding_status' => '打款状态：pending=待打款 / funded=已打款 / refunded=已退款。',
        'withdraw_records.funding_payload_hash' => '打款负载 SHA-256：防篡改。',
        'withdraw_records.refund_mt4_ticket' => '退款 MT4 凭证。',
        'withdraw_records.refund_time' => '退款完成时间。',
        'withdraw_records.funding_error_code' => '打款失败错误码。',

        // ---------- 框架表 ----------
        'failed_jobs.id' => '主键标识。',
        'failed_jobs.uuid' => '任务唯一标识（队列系统生成）。',
        'failed_jobs.connection' => '队列连接名（redis/database/sync）。',
        'failed_jobs.queue' => '队列名。',
        'failed_jobs.payload' => '任务序列化负载（JSON）。',
        'failed_jobs.exception' => '异常堆栈（JSON 序列化）。',
        'failed_jobs.failed_at' => '失败时间。',
        'migrations.id' => '主键标识。',
        'migrations.migration' => '迁移文件名（含时间戳前缀）。',
        'migrations.batch' => '迁移批次号：同批执行的迁移共享批次。',
        'password_resets.email' => '申请重置密码的邮箱。',
        'password_resets.token' => '重置令牌（哈希存储）。',
        'password_resets.created_at' => '令牌创建时间。',
        'personal_access_tokens.id' => '主键标识。',
        'personal_access_tokens.tokenable_type' => '令牌持有者模型类名。',
        'personal_access_tokens.tokenable_id' => '令牌持有者模型主键。',
        'personal_access_tokens.name' => '令牌名称（用途标识）。',
        'personal_access_tokens.token' => '令牌哈希（SHA-256，不存明文）。',
        'personal_access_tokens.abilities' => '令牌能力（JSON 数组，如 ["*"]）。',
        'personal_access_tokens.last_used_at' => '最后使用时间。',
        'personal_access_tokens.created_at' => '创建时间。',
        'personal_access_tokens.updated_at' => '更新时间。',
        'users.id' => '主键标识。',
        'users.name' => '用户名（框架默认字段）。',
        'users.email' => '邮箱（框架默认字段）。',
        'users.email_verified_at' => '邮箱验证时间。',
        'users.password' => '密码哈希（框架默认字段）。',
        'users.remember_token' => '记住登录令牌。',
        'users.created_at' => '创建时间。',
        'users.updated_at' => '更新时间。',

        // ---------- menus / permissions / news_langs / user_auths 时间戳等 ----------
        'menus.id' => '主键标识。',
        'menus.created_at' => '创建时间。',
        'menus.updated_at' => '更新时间。',
        'menus.deleted_at' => '软删除时间。',
        'permissions.id' => '主键标识。',
        'permissions.created_at' => '创建时间。',
        'permissions.updated_at' => '更新时间。',
        'permissions.deleted_at' => '软删除时间。',
        'news_langs.active_translation_key' => '当前生效的翻译 key：指向 news_langs 中实际展示的语言条目。',
        'user_auths.bank_no_tmp' => '银行卡号临时值：换卡流程中的新卡号（审核通过后覆盖正式字段）。',
        'user_auths.bank_name_tmp' => '开户行临时值：换卡流程中的新开户行。',
        'user_auths.bank_card_back_img' => '银行卡背面照片：实名/绑卡审核资料。',
        'user_auths.bank_card_back_img_tmp' => '银行卡背面照片临时值：换卡流程新卡背面照。',
        'user_auths_backup_20260613035755.bank_no_tmp' => '银行卡号临时值（历史备份表，字段语义同 user_auths）。',
        'user_auths_backup_20260613035755.bank_name_tmp' => '开户行临时值（历史备份表，字段语义同 user_auths）。',
        'user_auths_backup_20260613035755.bank_card_back_img' => '银行卡背面照片（历史备份表，字段语义同 user_auths）。',
        'user_auths_backup_20260613035755.bank_card_back_img_tmp' => '银行卡背面照片临时值（历史备份表，字段语义同 user_auths）。',
        'user_auths_backup_20260613040006.bank_no_tmp' => '银行卡号临时值（历史备份表，字段语义同 user_auths）。',
        'user_auths_backup_20260613040006.bank_name_tmp' => '开户行临时值（历史备份表，字段语义同 user_auths）。',
        'user_auths_backup_20260613040006.bank_card_back_img' => '银行卡背面照片（历史备份表，字段语义同 user_auths）。',
        'user_auths_backup_20260613040006.bank_card_back_img_tmp' => '银行卡背面照片临时值（历史备份表，字段语义同 user_auths）。',
    ],
];
